import Head from "next/head";
import Footer from "../Footer";
import Header from "../Header";
import Job from "../Job";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200&family=Roboto:ital,wght@0,400;1,300;1,400;1,500&display=swap" rel="stylesheet" />

      </Head>
      <Header />
      <Job />
      <Footer />
    </div>
  );
}
